services:
  api:
    build: .
    container_name: aniapi
    ports:
      - "3001:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/aniapi}
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo
    volumes:
      - ./mongodata:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - default